services:
  postgres:
    image: postgres:15
    container_name: hotelcrm-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotelcrm
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: mikepass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
